name: Pipeline DDS

on:
  push:
    branches:
      - "**"    # This triggers the pipeline on push for any branch
  pull_request:
    branches:
      - "**"    # This triggers the pipeline on pull requests for any branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Set up Maven cache
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn -B clean package -DskipTests

      - name: Test with Maven
        run: mvn -B test
        env:
          ACTIONS_RUNNER_DEBUG: true
          ACTIONS_STEP_DEBUG: true

      - name: Run Checkstyle
        run: mvn checkstyle:check
