name: Pipeline DDS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: List project directory
        run: ls -R

      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests

      - name: Test with Maven (HSQLDB)
        env:
          DB_URL: jdbc:hsqldb:mem:app-db
          DB_USER: sa
          DB_PASSWORD: ""
        run: mvn test -Dtest.persistence.unit=test-persistence-unit

      - name: Run Checkstyle
        run: mvn checkstyle:check
